### ISSUE TITLE
Create Tabular view of the Data and show meta data related to query like RTT (3)

### ISSUE THREAD

**Issue by AayushTyagi1** [couchbaselabs/VSCode-Couchbase#250]
- [x] Fetch Table component from capella
- [x] Show Query metadata
- [x] Create three tabs to represent data in JSON, Tabular and Plan format
